// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: service.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MinibinServiceClient is the client API for MinibinService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MinibinServiceClient interface {
	Upload(ctx context.Context, in *UploadRequest, opts ...grpc.CallOption) (*UploadResponse, error)
}

type minibinServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMinibinServiceClient(cc grpc.ClientConnInterface) MinibinServiceClient {
	return &minibinServiceClient{cc}
}

func (c *minibinServiceClient) Upload(ctx context.Context, in *UploadRequest, opts ...grpc.CallOption) (*UploadResponse, error) {
	out := new(UploadResponse)
	err := c.cc.Invoke(ctx, "/minibin.MinibinService/Upload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MinibinServiceServer is the server API for MinibinService service.
// All implementations must embed UnimplementedMinibinServiceServer
// for forward compatibility
type MinibinServiceServer interface {
	Upload(context.Context, *UploadRequest) (*UploadResponse, error)
	mustEmbedUnimplementedMinibinServiceServer()
}

// UnimplementedMinibinServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMinibinServiceServer struct {
}

func (UnimplementedMinibinServiceServer) Upload(context.Context, *UploadRequest) (*UploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedMinibinServiceServer) mustEmbedUnimplementedMinibinServiceServer() {}

// UnsafeMinibinServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MinibinServiceServer will
// result in compilation errors.
type UnsafeMinibinServiceServer interface {
	mustEmbedUnimplementedMinibinServiceServer()
}

func RegisterMinibinServiceServer(s grpc.ServiceRegistrar, srv MinibinServiceServer) {
	s.RegisterService(&MinibinService_ServiceDesc, srv)
}

func _MinibinService_Upload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinibinServiceServer).Upload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/minibin.MinibinService/Upload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinibinServiceServer).Upload(ctx, req.(*UploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MinibinService_ServiceDesc is the grpc.ServiceDesc for MinibinService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MinibinService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "minibin.MinibinService",
	HandlerType: (*MinibinServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upload",
			Handler:    _MinibinService_Upload_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
